### ISSUE TITLE
Idempotent?

### ISSUE THREAD

**Issue by dgoade55** [geerlingguy/ansible-role-aws-inspector#2]
Hey Jeff -- this isn't idempotent is it?

**Comment by geerlingguy** [comment]
@dgoade55 - If you run it twice in a row, yes (e.g. how the automated CI tests do it). By default the `aws_inspector_installer_dest` is in the /tmp directory, so after a reboot the task that downloads the installer will re-download the installer.

But if you change `aws_inspector_installer_dest` to a path that is not cleared out after reboot, then the role will always be idempotent for any given version of the awsagent.

If you're finding a case where this is not so, please open a new issue with steps to reproduce, etc.

**Comment by dgoade55** [comment]
Ah yes, great idea! Thank you for all of your contributions.
