### ISSUE TITLE
Default AWS Inspector URL no longer valid

### ISSUE THREAD

**Issue by nc-fosterr** [geerlingguy/ansible-role-aws-inspector#9]
The default URL to install AWS Inspector is no longer valid. This line needs to change:

https://github.com/geerlingguy/ansible-role-aws-inspector/blob/c355e202e5d731fe4ed831ec61795dd4bbacbfb5/defaults/main.yml#L2

to:

`aws_inspector_url: https://inspector-agent.amazonaws.com/linux/latest/install`

Per documentation:

https://docs.aws.amazon.com/inspector/latest/userguide/inspector_installing-uninstalling-agents.html#install-linux

**Comment by geerlingguy** [comment]
Fixed via #7.
